name: DigitalCloud Ninja Pipeline (CI/CD)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub and USER
  REGISTRY: docker.io
  USERNAME: digitalcloudninja

  # Container repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java (JDK) Version 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

#      - name: Publish Package to GitHub
#        run: ./gradlew publish
#        env:
#          USERNAME: ${{ github.actor }}
#          TOKEN: ${{ secrets.PKG_TOKEN }}

      - name: Container Registry Authentication
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Container
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Publish Container
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
